
package TPO_10.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPerson", targetNamespace = "http://TPO10/person")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPerson {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List&lt;TPO_10.proxy.Person&gt;
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sortByBirthDate", targetNamespace = "http://TPO10/person", className = "TPO_10.proxy.SortByBirthDate")
    @ResponseWrapper(localName = "sortByBirthDateResponse", targetNamespace = "http://TPO10/person", className = "TPO_10.proxy.SortByBirthDateResponse")
    @Action(input = "http://TPO10/person/IPerson/sortByBirthDateRequest", output = "http://TPO10/person/IPerson/sortByBirthDateResponse")
    public List<Person> sortByBirthDate(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Person> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List&lt;TPO_10.proxy.Person&gt;
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sortBySurname", targetNamespace = "http://TPO10/person", className = "TPO_10.proxy.SortBySurname")
    @ResponseWrapper(localName = "sortBySurnameResponse", targetNamespace = "http://TPO10/person", className = "TPO_10.proxy.SortBySurnameResponse")
    @Action(input = "http://TPO10/person/IPerson/sortBySurnameRequest", output = "http://TPO10/person/IPerson/sortBySurnameResponse")
    public List<Person> sortBySurname(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Person> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
